
services:
  db:
    image: postgres:16.1
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-ttai_password}
      - POSTGRES_USER=${DATABASE_USER:-ttai_user}
      - POSTGRES_DB=${DATABASE_NAME:-ttai_db}
      - POSTGRES_PORT=${DATABASE_PORT:-5432}
    expose:
      - ${DATABASE_PORT:-5432}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER:-ttai_user} -d ${DATABASE_NAME:-ttai_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  backend:
    build: ./backend
    env_file:
      - .env
    command: uvicorn app.web:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/app
    depends_on:
      backend:
        condition: service_healthy
    
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend_network


volumes:
  pg_data:
  rabbitmq_data:

networks:
  backend_network: