name: Backend Tests

on:
  push:
    paths:
      - 'backend/**'
      - 'docker-compose.test.yml'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'backend/**'
      - 'docker-compose.test.yml'
      - '.github/workflows/backend-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build test environment
      run: |
        docker compose -f docker-compose.test.yml up --build backend

    - name: Cleanup
      run: |
        docker compose -f docker-compose.test.yml down 