name: Backend Linters

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-lint.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    
    - name: Run Pylint
      run: |
        cd backend
        pylint app tests --disable=all --enable=C0114,C0115,C0116,C0411,W0611,W1201,W0401,W0231
        # code quality rules
        # C0114 - missing-module-docstring
        # C0115 - missing-class-docstring
        # C0116 - missing-function-docstring
        # C0411 - wrong-import-order
        # W0611 - unused-import
        # W1201 - logging-not-lazy
        # W0401 - wildcard-import
        # W0231 - super-init-not-called