name: Frontend Linters

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-lint.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    
    - name: Run ESLint
      run: |
        cd frontend
        npm run lint 